### ISSUE TITLE
Modifying and updating

### ISSUE THREAD

**Issue by sarthakdubeyy12** [nithingooud/nithin-portfolio#7]
Hi!!, i have asked you to share your portfolio project repository to me and you have shared your repository link to me on instagram and currently i am working on this portfolio application where i want to add some more sections in it like skills, academic, achievement and many more sections, which will make it more enhansive and more responsive so could you please give permission to me so that i can work on it

**Comment by PATILSAURA** [comment]
Yes, of course you can.

**Comment by sarthakdubeyy12** [comment]
![Screenshot from 2024-09-02 17-19-16](https://github.com/user-attachments/assets/e16a570e-c8d5-4a57-8d1b-ea282003018d)
But it is asking for permission from your end
